"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "./app/src/main/res"

"preserve_hierarchy": true

"files": [
  {
    "source": "/values/strings.xml",
    "translation": "/values-%android_code%/strings.xml"
  },
]