"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "./app/src/main/res"

"preserve_hierarchy": true

"files": [
  {
    "source": "./app/src/main/res/values/strings.xml",
    "translation": "./app/src/main/res/values-%android_code%/strings.xml"
  },
  {
    "source": "metadata/%locale%/full_description.txt",
    "translation": "metadata/%locale%.yml/full_description.txt"
  },
  {
    "source": "metadata/%locale%/short_description.txt",
    "translation": "metadata/%locale%.yml/short_description.txt"
  },
]